Adding max share and fee support
Banno/banno-powerons pull request #149
Opened 2022-11-15 14:45 UTC by rrobison44

Added new features:
- Added code that limits the maximum number of shares of each type that can be created.
- Added new account fee support.

[Jira CUS-1930](https://banno-jha.atlassian.net/browse/CUS-1930)

2022-11-16 22:07 UTC, tkainz commented
Robbie…..

I’m seeing a lot of commits for this PR.  Should I wait until you quit updating it before doing the peer review or…?

From: Robby Robison ***@***.***>
Sent: Tuesday, November 15, 2022 7:45 AM
To: Banno/banno-powerons ***@***.***>
Cc: Thomas Kainz ***@***.***>; Review requested ***@***.***>
Subject: Re: [Banno/banno-powerons] Adding max share and fee support (PR #149)


EXTERNAL EMAIL - Do not open attachments or click links from an unknown source. Forward suspicious emails to Anti-Spam.

@rrobison44<https://github.com/rrobison44> requested review from @Banno/team-poweron on: #149<https://github.com/Banno/banno-powerons/pull/149> Adding max share and fee support as a code owner.

—
Reply to this email directly, view it on GitHub<https://github.com/Banno/banno-powerons/pull/149#event-7814677836>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AOLSKBNBKP63OO7WF3QO7Y3WIOOXXANCNFSM6AAAAAASBATZ5M>.
You are receiving this because your review was requested.Message ID: ***@***.******@***.***>>
NOTICE: This electronic mail message and any files transmitted with it are intended
exclusively for the individual or entity to which it is addressed. The message, 
together with any attachment, may contain confidential and/or privileged information.
Any unauthorized review, use, printing, saving, copying, disclosure or distribution 
is strictly prohibited. If you have received this message in error, please 
immediately advise the sender by reply email and delete all copies.

2022-11-17 15:39 UTC, rrobison44 commented
Hi Tom.  You can review now.  I think I am mostly done with the updates.

Robby P. Robison | Staff Software Engineer | Digital Custom Development
[Logo, company name  Description automatically generated]



From: tkainz ***@***.***>
Date: Wednesday, November 16, 2022 at 3:09 PM
To: Banno/banno-powerons ***@***.***>
Cc: Robby Robison ***@***.***>, Mention ***@***.***>
Subject: Re: [Banno/banno-powerons] Adding max share and fee support (PR #149)

EXTERNAL EMAIL - Do not open attachments or click links from an unknown source. Forward suspicious emails to Anti-Spam.
Robbie…..

I’m seeing a lot of commits for this PR. Should I wait until you quit updating it before doing the peer review or…?

From: Robby Robison ***@***.***>
Sent: Tuesday, November 15, 2022 7:45 AM
To: Banno/banno-powerons ***@***.***>
Cc: Thomas Kainz ***@***.***>; Review requested ***@***.***>
Subject: Re: [Banno/banno-powerons] Adding max share and fee support (PR #149)


EXTERNAL EMAIL - Do not open attachments or click links from an unknown source. Forward suspicious emails to Anti-Spam.

@rrobison44<https://github.com/rrobison44> requested review from @Banno/team-poweron on: #149<https://github.com/Banno/banno-powerons/pull/149> Adding max share and fee support as a code owner.

—
Reply to this email directly, view it on GitHub<https://github.com/Banno/banno-powerons/pull/149#event-7814677836>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AOLSKBNBKP63OO7WF3QO7Y3WIOOXXANCNFSM6AAAAAASBATZ5M>.
You are receiving this because your review was requested.Message ID: ***@***.******@***.***>>
NOTICE: This electronic mail message and any files transmitted with it are intended
exclusively for the individual or entity to which it is addressed. The message,
together with any attachment, may contain confidential and/or privileged information.
Any unauthorized review, use, printing, saving, copying, disclosure or distribution
is strictly prohibited. If you have received this message in error, please
immediately advise the sender by reply email and delete all copies.


—
Reply to this email directly, view it on GitHub<https://github.com/Banno/banno-powerons/pull/149#issuecomment-1317734428>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AXE6DMAYGVWL4GYVEWTAZQDWIVLKNANCNFSM6AAAAAASBATZ5M>.
You are receiving this because you were mentioned.Message ID: ***@***.***>
NOTICE: This electronic mail message and any files transmitted with it are intended
exclusively for the individual or entity to which it is addressed. The message, 
together with any attachment, may contain confidential and/or privileged information.
Any unauthorized review, use, printing, saving, copying, disclosure or distribution 
is strictly prohibited. If you have received this message in error, please 
immediately advise the sender by reply email and delete all copies.

2022-11-18 16:00 UTC, jucarson requested changes
Robby, Three things besides the comments in the code... 

1. I believe you'll want to add the fee amount to the procedure CHECKSHAREIDS to remove a share type that has too high of a transfer amount AND fee amount so they can't pick it to begin with. 
2. Same with the max IDs... Should we just remove it from the list if they match that criteria? Seems crazy to do it both here and in the GETTERMSFUNDING state but could avoid errors.
3. Should all these changes be wrapped up inside the test account condition so it can be tested by certain users?

2022-11-28 10:57 UTC, rrobison44 commented on open-subshare/open-subshare-json-contract.md
> +          "memberAccountNumber": "1234567890S1234",
Fixed

2022-11-28 10:57 UTC, rrobison44 commented on open-subshare/open-subshare-json-contract.md
> +          "memberAccountNumber": "1234567890S1234",
Fixed

2022-11-28 11:04 UTC, rrobison44 commented on open-subshare/REPWRITERSPECS/BANNO.NEWSUBCREATE.V1.POW
>   PROGRAMUPDATENOTE1="Copy name functionality added"
Done

2022-11-28 11:24 UTC, rrobison44 commented on open-subshare/REPWRITERSPECS/BANNO.NEWSUBCREATE.V1.POW
> +       IF ERRORCODE<>0 THEN
I fixed this.  Added the error 506 back in.
```       IF ERRORCODE=0 THEN
        DO
         GETSHARETRANSFERRUN=TRANSFERRUNINITIAL
         CALL GETSHARETRANSFERS
         IF VALUE(SACFUNDREQUIREFLAG)>0 AND
            XFERSHAREFOUND=0 THEN
          ERRORCODE=506   
        END
```

2022-11-28 11:25 UTC, rrobison44 commented on open-subshare/open-subshare-json-contract.md
> +      ],
Done

2022-11-28 11:40 UTC, rrobison44 commented
To address some of Justin's additional comments:

1. I believe you'll want to add the fee amount to the procedure CHECKSHAREIDS to remove a share type that has too high of a transfer amount AND fee amount so they can't pick it to begin with.  **[RR] I think it would get kind of messy if we added this to CHECKSHAREIDS.  We would basically have to run the fee PO against each share.  And since the electronic transfer share list is built in the initial state, I'm not sure how easy it would be to adjust the share list after a fee has been calculated in the GETTERMSFUNDING state.  Maybe we just need to add some additional error handling further down stream??**
2. Same with the max IDs... Should we just remove it from the list if they match that criteria? Seems crazy to do it both here and in the GETTERMSFUNDING state but could avoid errors.  **[RR] The design didn't specify that these share types that already equal or exceed the max should be excluded from the initial selection in the UX.  We are just supposed to display an error if they pick one that already at that max count.  I suppose we could run this by the BA to see if they want to change the design.**
3. Should all these changes be wrapped up inside the test account condition so it can be tested by certain users? **[RR]Not sure about this**

2022-11-29 13:55 UTC, jucarson commented on open-subshare/REPWRITERSPECS/BANNO.NEWSUBCREATE.V1.POW
>   CONFIGPROGRAMMINDATE='10/20/22'
Sounds good

2022-11-29 14:36 UTC, jucarson reviewed
On the additional comments.. 

1. I see what you mean here, Maybe checking to be sure SACFEESHARECOUNT>0 at the end of the GETSACFEEINFO procedure would work? If not, throw an error 506 or create a new error. Looks like if there are no shares found, the JSON will just return an empty element and no errors are encountered but they won't be able to continue.

2. It's up to you if you want to check with the BA. Perhaps it makes more sense the way it is so the user knows why they can't open that type instead of it just being missing from the selection screen. 

3. Are there going to be changes to the UX so that a CU that's already live with an older version could test it using the Banno People permissions (i.e a different external application name)? If not, then all the changes should be conditional based on the TESTACCOUNT and TESTMODE flags and the old condition (for the last set of changes) should be removed. Looks like for this PowerOn's last changes, Tom just set the new variables to what they would be if the CU did not have the new parameter settings defined. Doing it that way makes it pretty easy.. See the end procedure SETTESTACCTSTATUS.

2022-11-30 14:55 UTC, tkainz requested changes
Robby.... just posting these notes I have so far. I'm still feeling - with what you're working on with Justin - that I'm aiming at a moving target

2022-12-06 03:25 UTC, rrobison44 commented on open-subshare/REPWRITERSPECS/BANNO.NEWSUBCREATE.FEES.V1.POW
> + IF SACFEECOUNT<SACFEEMAX THEN
Done.  I went ahead and added but this is not an error we should ever see in reality.  That would be a lot of fees.  But it doesn't hurt to add it.

2022-12-06 03:31 UTC, rrobison44 commented on open-subshare/REPWRITERSPECS/BANNO.NEWSUBCREATE.V1.CONFIG
> + SACERRORCODEDEFAULTCHR(12)="No more shares of this type can be created"
Added comment in the PowerOn section of the review.

2022-12-06 03:35 UTC, rrobison44 commented on open-subshare/REPWRITERSPECS/BANNO.NEWSUBCREATE.V1.CONFIG
> +   HTMLVIEWLINE("</td><td class='width100-'></td><td class='plsMin width50'>")
Fixed typo.

2022-12-06 03:40 UTC, rrobison44 commented on open-subshare/REPWRITERSPECS/BANNO.NEWSUBCREATE.V1.CONFIG
> +     HTMLVIEWLINE("<td>")
Looks like that was a bug in the original code.  Fixed.  Browser must handle it ok, though.

2022-12-06 03:43 UTC, rrobison44 commented on open-subshare/REPWRITERSPECS/BANNO.NEWSUBCREATE.V1.CONFIG
>   Q=CTRLCHR(34)
Done.

2022-12-06 03:48 UTC, rrobison44 commented on open-subshare/REPWRITERSPECS/BANNO.NEWSUBCREATE.V1.CONFIG
> -                                          SACSHARETYPES(TEMPNUM,TEMPNUM2)
Yes, I believe this was a bug or code that was not required.  I may need to go back and figure out exactly what I was fixing.

2022-12-06 04:25 UTC, rrobison44 commented on open-subshare/REPWRITERSPECS/BANNO.NEWSUBCREATE.V1.CONFIG
> +  END
Done.

2022-12-20 18:18 UTC, rrobison44 commented
> On the additional comments..
> 
> 1. I see what you mean here, Maybe checking to be sure SACFEESHARECOUNT>0 at the end of the GETSACFEEINFO procedure would work? If not, throw an error 506 or create a new error. Looks like if there are no shares found, the JSON will just return an empty element and no errors are encountered but they won't be able to continue.
> 2. It's up to you if you want to check with the BA. Perhaps it makes more sense the way it is so the user knows why they can't open that type instead of it just being missing from the selection screen.
> 3. Are there going to be changes to the UX so that a CU that's already live with an older version could test it using the Banno People permissions (i.e a different external application name)? If not, then all the changes should be conditional based on the TESTACCOUNT and TESTMODE flags and the old condition (for the last set of changes) should be removed. Looks like for this PowerOn's last changes, Tom just set the new variables to what they would be if the CU did not have the new parameter settings defined. Doing it that way makes it pretty easy.. See the end procedure SETTESTACCTSTATUS.

[RR] (1) I implemented the SACFEESHARECOUNT>0 check as Justin suggested.  We will return error code 506 now in the condition where no fee shares are available to cover the amount of the fee. (2) No changes for now. (3) I still need to see how the test mode works and whether it is feasible in this situation.  But they can test the fees by just adding checks for account numbers in the fee specfile (i.e. only return a fee for the test accounts).  Also, for the share type create max, they can just set this max on a single group.

2022-12-20 19:15 UTC, rrobison44 commented
> Robby.... just posting these notes I have so far. I'm still feeling - with what you're working on with Justin - that I'm aiming at a moving target. Also... I couldn't seem to find any code which actually posts the calculated fees... where am I not looking? Ohhh. also, because these changes pertain to the "library" version, I think it'd be prudent to have as many looks as possible. Jordan is pretty good at catching a lot of small details.

[RR] Fixed issue with missing fee posting code.

2022-12-23 14:18 UTC, jucarson approved these changes
Looks like everything I found has been resolved and the TRANPERFORM for the fee is now in there. I approve, looks good. LMK if what you decide on the test accounts item.

2023-01-05 05:41 UTC, merged