Update Error Codes in JSon Contract for BANNO CD Renew
Banno/banno-powerons pull request #178
Opened 2024-01-16 20:00 UTC by jordan-keenan

Updated error codes in JSon contract for BANNO CD renew and corrected letter file read error

2024-01-22 19:04 UTC, tkainz requested changes
Just one item pertaining to error code 500

2024-01-25 00:45 UTC, jordan-keenan commented on certificate-renewal/Certificate Renewal JSON contract.md
> +| 500        | Undefined Error || Generic Error |
Thanks Tom. I've changed it to say "Program running in memo mode". That will be in the next commit

2024-01-25 00:46 UTC, jordan-keenan commented on certificate-renewal/Certificate Renewal JSON contract.md
> +| 506        | Renew options not set for Share type | : 1234 ||
Made the change. It will be in next commit.

2024-01-25 00:46 UTC, jordan-keenan commented on certificate-renewal/Certificate Renewal JSON contract.md
> +|            || : Acct Type 1234 ||
Made the change. It will be in next commit.

2024-01-25 00:46 UTC, jordan-keenan commented on certificate-renewal/Certificate Renewal JSON contract.md
> +| 502        | Invalid account or share | : Acct or Share Warning 123 ||
Made the change. It will be in next commit.

2024-01-25 17:30 UTC, rrobison44 approved these changes
Latest changes look good.

2024-01-25 20:25 UTC, tkainz commented on certificate-renewal/Certificate Renewal JSON contract.md
> +| 500        | Undefined Error || Generic Error |
looks good - thanks

2024-01-25 20:29 UTC, jordan-keenan commented on certificate-renewal/Certificate Renewal JSON contract.md
> +| 500        | Undefined Error || Generic Error |
Thanks @tkainz , Can you approve the PR?

Also, Sorry I got behind. I'm going to look at your Share/Loan List build procedures now (starting after lunch), and then M2M.

2024-01-25 20:31 UTC, tkainz approved these changes

2024-01-25 22:12 UTC, merged