BANNO.ODTOPTIN.V1.POW Add PID parameter
Banno/banno-powerons pull request #190
Opened 2024-05-14 16:22 UTC by tkainz

Added parameter for program installation date.

2024-05-15 12:15 UTC, jucarson approved these changes
Looks good.

2024-05-15 15:55 UTC, rrobison44 requested changes
Added one comment.

2024-05-15 15:55 UTC, rrobison44 commented on odt-opt-in/REPWRITERSPECS/BANNO.ODTOPTIN.V1.POW
> + PRINT "    "+Q+"programInstallDate"+Q+": "+Q+FORMAT("99/99/99",LASTMODDATE)+Q
Should this be PARAMINSTALLDATE?

2024-05-15 16:10 UTC, tkainz commented on odt-opt-in/REPWRITERSPECS/BANNO.ODTOPTIN.V1.POW
> + PRINT "    "+Q+"programInstallDate"+Q+": "+Q+FORMAT("99/99/99",LASTMODDATE)+Q
Corrected @rrobison44  - thanks

2024-05-16 16:47 UTC, rrobison44 approved these changes
Changes look good.

2024-05-28 19:04 UTC, jordan-keenan approved these changes
@tkainz Code looks good, Approved!
Only thing I found was spelling of Instuctions around line 608 "** SI PARAMSERVICEINST Service Instuctions"

2024-05-28 19:04 UTC, jordan-keenan commented on odt-opt-in/REPWRITERSPECS/BANNO.ODTOPTIN.V1.POW
>  **  SI  PARAMSERVICEINST      Service Instuctions
@tkainz Code looks good, Approved!
Only thing I found was spelling of Instuctions around line 608 "** SI PARAMSERVICEINST Service Instuctions"

2024-06-03 13:45 UTC, merged