Create BANNO.CHANGE.ADDR.V1.POW
Banno/banno-powerons pull request #67
Opened 2021-03-01 21:56 UTC by tkainz

BANNO.CHANGE.ADDR.V1.POW

2021-03-02 21:46 UTC, jucarson requested changes

2021-03-02 21:46 UTC, jucarson commented on change-address/REPWRITERSPECS/BANNO.CHANGE.ADDR.V1.POW
> +** PASS    @RGUSERCHR2  City | Stata | Zipcode
Type Stata should be State

2021-03-02 21:46 UTC, jucarson commented on change-address/REPWRITERSPECS/BANNO.CHANGE.ADDR.V1.POW
> +[* Check character string and remove out any characters or hidden
"remove out" should be simply"remove"

2021-03-02 21:46 UTC, jucarson commented on change-address/REPWRITERSPECS/BANNO.CHANGE.ADDR.V1.POW
> +** PO Box address be found, set an error code and create a
"be found" should be "is found"

2021-03-02 21:46 UTC, jucarson commented on change-address/REPWRITERSPECS/BANNO.CHANGE.ADDR.V1.POW
> +** RETURN  PARAMSETWARNINGEXPIRATION  Caldulated warning expiration date for WARNINGTOSET
Caldulated should be Calculated

2021-03-02 21:46 UTC, jucarson commented on change-address/REPWRITERSPECS/BANNO.CHANGE.ADDR.V1.POW
> +** RETURN  RESPONSECODE  Error code pertinant to error type
pertinant should be pertinent

2021-03-02 23:05 UTC, tkainz commented on change-address/REPWRITERSPECS/BANNO.CHANGE.ADDR.V1.POW
> +** PASS    @RGUSERCHR2  City | Stata | Zipcode
Corrected

2021-03-02 23:05 UTC, tkainz commented on change-address/REPWRITERSPECS/BANNO.CHANGE.ADDR.V1.POW
> +[* Check character string and remove out any characters or hidden
Corrected

2021-03-02 23:06 UTC, tkainz commented on change-address/REPWRITERSPECS/BANNO.CHANGE.ADDR.V1.POW
> +** PO Box address be found, set an error code and create a
Corrected

2021-03-02 23:06 UTC, tkainz commented on change-address/REPWRITERSPECS/BANNO.CHANGE.ADDR.V1.POW
> +** RETURN  PARAMSETWARNINGEXPIRATION  Caldulated warning expiration date for WARNINGTOSET
corrected

2021-03-02 23:06 UTC, tkainz commented on change-address/REPWRITERSPECS/BANNO.CHANGE.ADDR.V1.POW
> +** RETURN  RESPONSECODE  Error code pertinant to error type
corrected

2021-03-03 13:36 UTC, jucarson approved these changes
Looks good!

2021-03-26 21:08 UTC, merged