COA Documentation Update
Banno/banno-powerons pull request #93
Opened 2021-08-06 17:37 UTC by tkainz

Updated Banno change of address  README, JSON contract & questionnaire files

2021-08-09 13:16 UTC, jucarson requested changes
Just the 1 item!

2021-08-09 13:16 UTC, jucarson commented on change-address/README.md
> +* Add the program to SymXchange Common parameters and refresh SymXchange
Should this say both programs?

2021-08-09 13:20 UTC, tkainz commented on change-address/README.md
> +* Add the program to SymXchange Common parameters and refresh SymXchange
Yes indeed.  TY

2021-08-09 13:35 UTC, jucarson approved these changes
Looks Good

2021-08-09 22:27 UTC, jordan-keenan approved these changes
Code looks good!

2021-08-20 12:37 UTC, christinasimms approved these changes
Good to go

2021-08-20 13:15 UTC, merged